#!/bin/bash

echo "${CRON_SCHEDULE} MONGO_PORT_27017_TCP_ADDR=${MONGO_PORT_27017_TCP_ADDR} FTP_USER=${FTP_USER} FTP_PASSWORD=${FTP_PASSWORD} FTP_SERVER=${FTP_SERVER} /backup.sh" | crontab -
exec cron -f
